# Starter pipeline : AutoMerge Pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
resources:
  pipelines:
  - pipeline: deployPipeline   # Name of the pipeline resource
    source: deployPipeline # Name of the pipeline referenced by the pipeline resource

trigger:
  batch: "true"
  branches:
    include:
      - feature/Test1234

pr:
  autoCancel: "true"
  branches:
    include:
      - feature/Test1234
variables:
  - group: TestVariableGroup
  - name: patToken
    value: $[variables.PAT_TOKEN]
      
jobs:

- job: AutoMergeToMaster
  displayName: Auto Merge
  steps: 
  - checkout: self
    persistCredentials: true
    clean: true
    env:
      AZURE_DEVOPS_EXT_PAT: $(PAT_TOKEN)
  - powershell: |

       if($(allowAutoMerge) -eq 1){

          git --version
          git config --global user.email "Prashantsxn8@gmail.com"
          git config --global user.name "Prashantsaxena88811"
          git checkout feature/Test1234
          git pull origin feature/Test1234
          git checkout master
          git merge feature/Test1234
          git push origin master
          
          $env:AZURE_DEVOPS_EXT_PAT = 'f3s5p4b4soqlcef7yqjx3bwfpy5e6c4nw5f3wgwf3s7hw6ghvepa'
          az pipelines variable-group variable update --group-id 2 --name isCommitFromHotFix --value 1 --organization https://dev.azure.com/PrashantsaxenaSF/ --project TestProject-Vivek
 
         }else {
          write-host("No Auto Merge")
       }

 