//a comment
@isTest
public with sharing class BeerQualityInspectionTest {

    public BeerQualityInspectionTest() {

    }
    @isTest
    static void aromaticHopFlavoringTest() {
        myclass demo = new myclass();
        System.assertEquals(demo.getAppVersion(), '1.0.0');
    }
    @isTest
    static void bitterBeerFaceTest() {
        myclass demo = new myclass();
        System.assertEquals(demo.getAppVersion(), '1.0.0');
    }
    @isTest
    static void bottlesAndCansTest() {
        myclass demo = new myclass();
        System.assertEquals(demo.getAppVersion(), '1.0.0');
    }
    @isTest
    static void insufficientCarbonationTest() {
        myclass demo = new myclass();
        System.assertEquals(demo.getAppVersion(), '1.0.0');
    }
    @isTest
    static void noRegretsTest() {
        myclass demo = new myclass();
        System.assertEquals(demo.getAppVersion(), '1.0.0');
    }
    @isTest
    static void srslyDidIGetDrunkTest() {
        myclass demo = new myclass();
        System.assertEquals(demo.getAppVersion(), '1.0.0');
    }
}
