@isTest
public class NuclearFusionTest {
    public NuclearFusionTest() {

    }
    @isTest
    static void deuteriumIsotopeStabilityTest() {
        myclass demo = new myclass();
        System.assertEquals(demo.getAppVersion(), '1.0.0');
    }
    @isTest
    static void tritiumIonizationTest() {
        myclass demo = new myclass();
        System.assertEquals(demo.getAppVersion(), '1.0.0');
    }
    @isTest
    static void nuclearCoulombForceRepulsionTest() {
        myclass demo = new myclass();
        System.assertEquals(demo.getAppVersion(), '1.0.0');
    }
    @isTest
    static void nucleosynthesisEndToEndTest() {
        myclass demo = new myclass();
        System.assertEquals(demo.getAppVersion(), '1.0.0');
    }
    @isTest
    static void lowTemperatureFusionReactionTest() {
        myclass demo = new myclass();
        System.assertEquals(demo.getAppVersion(), '1.0.0');
    }
}
