@isTest
public with sharing class WhoIsIgnoringUsTest {
    @isTest
    static void ActuallyListeningTest() {
        System.assertEquals(false, false);
    }
    @isTest
    static void CheckingEmailsThatCouldProbalbyWaitTest() {
        System.assertEquals(true, true);
    }
    @isTest
    static void FightingWithMosconeWifiTest() {
        System.assertEquals(true, true);
    }
    @isTest
    static void LookingUpNextSessionTest() {
        System.assertEquals(true, true);
    }
    @isTest
    static void TextingWifeAboutDinnerTest() {
        System.assertEquals(true, true);
    }
    @isTest
    static void TweetingPhotoOfPartyTest() {
        System.assertEquals(true, true);
    }
    @isTest
    static void UnitedAppCheckingFlightDelayTest() {
        System.assertEquals(true, true);
    }
}
